import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#EDEDED',
    },
    headerView: {
        width: '100%',
        borderBottomEndRadius: 20,
        borderBottomStartRadius: 20,
        backgroundColor: '#4a5a96',
        alignItems: 'center',
        height: 60,
        justifyContent: 'center',
    },
    topTitle: {
        fontSize: 20,
        fontWeight: '600',
        fontStyle: 'italic',
        color: 'white',
    },
    divider: {
        width: '90%',
        alignSelf: 'center',
        marginTop: 5,
    },
    searchView: {
        flexDirection: 'row',
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'space-between',
        alignContent: 'center',
        marginTop: 25,
        width: '85%',
    },
    searchBar: {
        width: '85%',
        height: 50,
        justifyContent: 'center',
        backgroundColor: 'white',
        elevation: 10,
        borderRadius: 10,
        borderWidth: 1,
    },
    filter: {
        width: 25,
        height: 25,
        top: 2,
    },
    ageFilterView: {
        alignSelf: 'center',
        width: '100%',
        marginTop: 20,
    },
    agefilterLabel: {
        fontSize: 16,
        marginBottom: 5,
        fontWeight: '600',
        color: 'black',
    },
    centeredView: {
        flex: 1,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
    },
    modalView: {
        width: '100%',
        height: 320,
        backgroundColor: 'white',
        borderRadius: 15,
        paddingVertical: 10,
        paddingHorizontal: 25,
        alignItems: 'center',
        elevation: 35,
        borderWidth: 2,
    },
    dropView: {
        alignSelf: 'flex-start',
        marginTop: 20,
        width: '100%',
    },
    dropdown: {
        height: 50,
        width: '100%',
        borderColor: 'grey',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 8,
        backgroundColor: 'white',
    },
    dropLabel: {
        fontSize: 15,
        fontWeight: '500',
        color: 'black',
        marginBottom: 5,
    },
    dropContainer: {
        borderBottomWidth: 1,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderColor: 'grey',
        maxHeight: 250,
    },
    selectedTextStyle: {
        fontSize: 16,
        color: '#11867F',
    },
    iconStyle: {
        width: 25,
        height: 25,
        tintColor: 'black',
    },
    dropItemText: {
        height: 22,
        color: 'black',
    },
    dropItem: {
        height: 45,
        justifyContent: 'center',
    },
    dropSearch: {
        height: 40,
        fontSize: 16,
        borderColor: 'black',
    },
    button: {
        borderRadius: 20,
        padding: 10,
        elevation: 2,
        marginLeft: 5,
    },
    buttonOpen: {
        backgroundColor: '#11867F',
    },
    buttonClose: {
        backgroundColor: 'red',
    },
    textStyle: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    modalText: {
        marginBottom: 15,
        textAlign: 'center',
    },
    pickerView: {
        width: '90%',
    },
    filterLabel: {
        fontSize: 16,
        marginBottom: 10,
        fontWeight: '600',
        color: 'black',
    },
    filterBtnView: {
        flexDirection: 'row',
        marginTop: 35,
        width: '100%',
        justifyContent: 'space-between',
    },
    resetBtn: {
        marginEnd: 65,
        borderWidth: 1,
        borderColor: 'grey',
    },
    safeContainerStyle: {
        flex: 1,
        margin: 20,
        justifyContent: 'center',
    },
    listView: {
        marginTop: 30,
        width: '100%',
    },
    emptyText: {
        marginTop: 20,
        fontSize: 17,
        color: '#c22710',
        fontWeight: '500',
        textAlign: 'center',
    },
    card: {
        borderRadius: 10,
        elevation: 3,
        width: '85%',
        margin: 9,
        borderWidth: 1,
        borderColor: 'darkgrey',
        marginBottom: 20,
        alignSelf: 'center',
    },
    cardImage: {
        width: '100%',
        height: 150,
        borderRadius: 10,
    },
    cardSubView: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    cardDetailView: {
        flexDirection: 'row',
        marginTop: 10,
        alignSelf: 'center',
        alignItems: 'center',
    },
    cardDetailView2: {
        width: '100%',
        flexDirection: 'row',
        marginTop: 10,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    cardLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: 'black',
        marginEnd: 5,
    },
    cardText: {
        fontSize: 16,
        fontWeight: '400',
        color: 'grey',
    },
    rankText: {
        fontSize: 16,
        fontWeight: '500',
        color: 'darkblue',
    },
    content: {
        marginTop: 10,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        marginTop: -5,
        color: '#4a5a96',
        textAlign: 'center',
    },
    locIcon: {
        width: 16,
        height: 16,
        marginRight: 5,
    },
    cityText: {
        fontSize: 16,
        color: 'black',
    },
    inviteBtn: {
        width: 80,
        height: 30,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
        borderRadius: 8,
        borderWidth: 1.5,
    },
    inviteText: {
        fontSize: 15,
        fontWeight: '600',
        color: 'black',
    },
    inviteIcon: {
        width: 15,
        height: 15,
        tintColor: 'black',
        marginLeft: 5,
        top: 1,
    },
    invitedBtn: {
        width: 80,
        height: 30,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#2abd89',
        borderRadius: 8,
    },
    invitedText: {
        fontSize: 15,
        fontWeight: '600',
        color: 'white',
    },
    invitedIcon: {
        width: 15,
        height: 15,
        tintColor: 'white',
        marginLeft: 5,
        top: 1,
    },
});

export default styles;
