import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#EDEDED',
    },
    modalBackground: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    activityIndicatorWrapper: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-around',
    },
    avatar: {
        alignSelf: 'center',
        borderWidth: 3,
        borderColor: '#143B63',
    },
    modalBackground: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailsContainer: {
        width: '90%',
        alignSelf: 'center',
        borderWidth: 2,
        borderColor: 'lightgrey',
        borderRadius: 10,
    },
    listTop: {
        borderTopStartRadius: 10,
        borderTopEndRadius: 10,
    },
    listBottom: {
        borderBottomStartRadius: 10,
        borderBottomEndRadius: 10,
    },
    icon: {
        width: 35,
        height: 35,
        marginRight: 10,
    },
    topView: {
        flexDirection: 'row',
        marginTop: 15,
        marginBottom: 20,
        paddingHorizontal: 20,
    },
    nameText: {
        fontSize: 20,
        fontWeight: '700',
        width: '100%',
    },
    usernameText: {
        fontSize: 17,
        marginTop: 5,
        width: '100%',
    },
    inviteBtn: {
        width: 100,
        height: 40,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
        borderRadius: 10,
        borderWidth: 1.5,
        marginTop: 20,
    },
    inviteText: {
        fontSize: 16,
        fontWeight: '700',
        color: 'black',
        letterSpacing: 0.5,
    },
    inviteIcon: {
        width: 16,
        height: 16,
        tintColor: 'black',
        marginLeft: 6,
        top: 1,
    },
    invitedBtn: {
        width: 100,
        height: 40,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
        borderRadius: 10,
        borderColor: '#1c658a',
        borderWidth: 1.5,
        marginTop: 20,
    },
    invitedText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1c658a',
        letterSpacing: 0.5,
    },
    invitedIcon: {
        width: 16,
        height: 16,
        tintColor: '#1c658a',
        marginLeft: 5,
        top: 1,
    },
    ageText: {
        fontSize: 18,
        color: 'grey',
        fontWeight: '500',
    },
    detailTitle: {
        fontSize: 17,
        fontWeight: '700',
    },
    detailText: {
        fontSize: 16,
    },
    requestBtnView: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        marginTop: 10,
    },
    chatButton: {
        width: 120,
        height: 65,
        backgroundColor: '#0084ff',
        borderRadius: 10,
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
        margin: 20,
    },
    acceptButton: {
        width: 90,
        height: 50,
        backgroundColor: '#13ba85',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        margin: 20,
    },
    removeButton: {
        width: 90,
        height: 50,
        backgroundColor: 'red',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        margin: 20,
    },
    addButton: {
        width: 120,
        height: 65,
        backgroundColor: '#0084ff',
        borderRadius: 10,
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
        margin: 20,
    },
    sentButton: {
        backgroundColor: '#e8c641',
    },
    unfriendButton: {
        backgroundColor: 'red',
    },
    addButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '700',
    },
});

export default styles;
